# Introducción a  Numpy

**Profesor:** Roberto Muñoz <br />
**E-mail:** <rmunoz@metricarts.com> <br />

**Colaborador:** Sebastián Arpón <br />
**E-mail:** <rmunoz@metricarts.com> <br />

Uno de los módulos más importantes de Python es **[Numpy](http://www.numpy.org/)**. El origen de Numpy se debe principalmente al diseñador de software Jim Hugunin quien diseñó el módulo Numeric para dotar a Python de capacidades de cálculo similares a las de otros softwares como MATLAB. Posteriormente, mejoró Numeric incorporando nuevas funcionalidades naciendo lo que hoy conocemos como Numpy.

Numpy es el encargado de añadir toda la capacidad matemática y vectorial a Python haciendo posible operar con cualquier dato numérico o array (posteriormente veremos qué es un array). Incorpora operaciones tan básicas como la suma o la multiplicación u otras mucho más complejas como la transformada de Fourier o el álgebra lineal. Además incorpora herramientas que nos permiten incorporar código fuente de otros lenguajes de programación como C/C++ o Fortran lo que incrementa notablemente su compatibilidad e implementación.


## ¿Porqué usar Numpy?

En múltiples ocasiones necesitamos hacer operaciones numéricas sobre datos provenientes de archivos Excel o Bases de datos que contienen múltiples campos (columnas) y múltiples registros (filas).

Vimos que en Python existen las listas, tuplas y diccionarios, las cuales son de gran ayuda para almacenar y adminsitrar datos. Veamos qué sucede cuando queremos sumar los elementos almacenados en dos listas.

In [1]:
x=[1,2,3,4]
y=[5,6,7,8]
print(x+y)

[1, 2, 3, 4, 5, 6, 7, 8]


Como podemos notar, el operador + simplemente concatena las dos listas.
¿Alguien sugiere como podriamos sumar los elmentos de las dos listas, elemento por elemento?

In [2]:
res=[]
for i in range(4):
    res.append(x[i]+y[i])
    
print(res)

[6, 8, 10, 12]


## Cómo importar el paquete Numpy

Partimos importando el paquete numpy usando la función import. En este caso usaremos el alias np para referirnos de manera más abreviada a las clases y  métodos implementados en numpy.

In [3]:
import numpy

In [4]:
import numpy as np
print(np.__version__)

1.13.3


In [5]:
help(np)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.


## Definición de arreglos en Numpy

In [11]:
x= np.array([1,2,3])
x

array([1, 2, 3])

In [12]:
x.shape

(3,)

In [13]:
x.size

3

In [14]:
x = np.array([[1,2,3,4],[5,6,7,8]])

In [15]:
# Definir un arreglo 2D

x = np.array([[1,2,3,4],[5,6,7,8]])

print(x)
print('type(x): ', type(x))
print('x.dtype: ', x.dtype)
print('x.size: ', x.size)
print('x.shape: ', x.shape)

[[1 2 3 4]
 [5 6 7 8]]
type(x):  <class 'numpy.ndarray'>
x.dtype:  int64
x.size:  8
x.shape:  (2, 4)


In [16]:
# Definir un arreglo 1D como tipo de dato de punto flotante

x = np.array([1,2,3,4], dtype=np.float32)
print(x)
print('type(x): ', type(x))
print('x.dtype: ', x.dtype)
print('x.size: ', x.size)
print('x.shape: ', x.shape)

[ 1.  2.  3.  4.]
type(x):  <class 'numpy.ndarray'>
x.dtype:  float32
x.size:  4
x.shape:  (4,)


In [19]:
x = np.array([1,2,3,4], dtype=np.float32)
y = np.array([5,6,7,8])

print(y.dtype)

int64


In [36]:
# Sumar los arreglos x e y
x = np.array([1,2,3,4], dtype=np.float32)
y = np.array([5,6,7,8])

print('x: ', x)
print('y: ', y)
print('Suma: ', x*y.T)

x:  [ 1.  2.  3.  4.]
y:  [5 6 7 8]
Suma:  [  5.  12.  21.  32.]


In [34]:
x = np.array([[1,2,3,4]], dtype=np.float32)
y = np.array([[5,6,7,8]])

print(x.shape)
print(y.shape)

print( np.dot(x, y.T) )

(1, 4)
(1, 4)
[[ 70.]]


In [37]:
x+10

array([ 11.,  12.,  13.,  14.], dtype=float32)

In [38]:
x = np.array([[1,2,3,4],[5,6,7,8]])
y = np.array([5,6,7,8])

print(x.shape)
print(y.shape)

(2, 4)
(4,)


In [41]:
z = x*y
print(z)

[[ 5 12 21 32]
 [25 36 49 64]]


In [42]:
z.shape

(2, 4)

In [50]:
# Definir un arreglo 2D

x= np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(type(x))
print(x.size)
print(x.shape)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
8
(2, 4)


In [52]:
x[0,0:2]

array([1, 2])

**See Figure 1 for an illustration of indexing on a 2D array.**<br />
<img src="images/numpy_indexing.png" width="400">

In [53]:
# Inicializar un arreglo 1D y otro 2D con ceros. Notar que usamos Y por X

x=np.zeros(10)
print('x: ', x)

y=np.zeros([2,4])
print('y:', y)

x:  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
y: [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [57]:
help(np.random.seed)

Help on built-in function seed:

seed(...) method of mtrand.RandomState instance
    seed(seed=None)
    
    Seed the generator.
    
    This method is called when `RandomState` is initialized. It can be
    called again to re-seed the generator. For details, see `RandomState`.
    
    Parameters
    ----------
    seed : int or array_like, optional
        Seed for `RandomState`.
        Must be convertible to 32 bit unsigned integers.
    
    See Also
    --------
    RandomState



In [72]:
# Crear un arreglo usando valores aleatorios entre 0 y 1
np.random.seed(10)

x=np.random.random(100)
print(x)

[ 0.77132064  0.02075195  0.63364823  0.74880388  0.49850701  0.22479665
  0.19806286  0.76053071  0.16911084  0.08833981  0.68535982  0.95339335
  0.00394827  0.51219226  0.81262096  0.61252607  0.72175532  0.29187607
  0.91777412  0.71457578  0.54254437  0.14217005  0.37334076  0.67413362
  0.44183317  0.43401399  0.61776698  0.51313824  0.65039718  0.60103895
  0.8052232   0.52164715  0.90864888  0.31923609  0.09045935  0.30070006
  0.11398436  0.82868133  0.04689632  0.62628715  0.54758616  0.819287
  0.19894754  0.8568503   0.35165264  0.75464769  0.29596171  0.88393648
  0.32551164  0.1650159   0.39252924  0.09346037  0.82110566  0.15115202
  0.38411445  0.94426071  0.98762547  0.45630455  0.82612284  0.25137413
  0.59737165  0.90283176  0.53455795  0.59020136  0.03928177  0.35718176
  0.07961309  0.30545992  0.33071931  0.7738303   0.03995921  0.42949218
  0.31492687  0.63649114  0.34634715  0.04309736  0.87991517  0.76324059
  0.87809664  0.41750914  0.60557756  0.51346663  0.5

In [110]:
# Extraer valores de un arreglo Numpy usando indices

x= np.array([[1,2,3,4],
            [5,6,7,8],
             [9,10,11,12]])
print(x)

print('\nx[0,3]: ', x[0,3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

x[0,3]:  4


In [74]:
print('\nx[:,0]: ', x[:,0])


x[:,0]:  [1 5 9]


In [91]:
y=x[:,0]
y.shape

(3,)

In [77]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
# Numpy permite crear máscaras fácilmente usando condiciones booleanas

a=x>6
print(a)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [100]:
x[a]

array([ 7,  8,  9, 10, 11, 12])

In [93]:
# Extraer los valores de x que satisfacen la condición booleana. Para ello usamos la máscara

y=x[:]
y[~a]=0
y

array([[ 0,  0,  0,  0],
       [ 0,  0,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
x=[1,2,3,4,5,6,7,8,9]

In [107]:
def mayor(x):
    if x>6:
        return True
    else:
        return False

In [108]:
y = filter(lambda n: n>6, x)
list(y)

[7, 8, 9]

In [109]:
x[x>2]

TypeError: '>' not supported between instances of 'list' and 'int'

**See Figure 2 for an illustration of boolean indexing on a 2D array.**<br />
<img src="images/boolean_indexing.png" width="400">

In [111]:
x.shape

(3, 4)

In [112]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [114]:
# Sumar los valores de un arreglo 2D a lo largo del eje Y (columnas)

np.sum(x, axis=0)

array([15, 18, 21, 24])

In [115]:
# Sumar los valores de un arrego 2D a lo largo del eje X (filas)

np.sum(x, axis=1)

array([10, 26, 42])

In [116]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [117]:
x.shape

(3, 4)

In [118]:
# Crear la transpuesta de la matriz x

y = x.T
print(y, y.shape)


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]] (4, 3)


## Funciones matemáticas

In [123]:
x=np.random.random(10)
#print(x)
print('Mean: ', np.mean(x))
print('StdDev: ', np.std(x))

Mean:  0.4896673126
StdDev:  0.273712402747


In [126]:
x=np.random.random(10000)
#print(x)
print('Mean: ', np.mean(x))
print('StdDev: ', np.std(x))

Mean:  0.500590042219
StdDev:  0.288375487445


In [128]:
x=np.random.randn(10000)
print('Mean: ', np.mean(x))
print('StdDev: ', np.std(x))

Mean:  0.0078109332332
StdDev:  1.00307632942


In [129]:
import numpy as np

In [130]:
# También es posible importar algunas funciones directamente desde las librerías
# Para ello usamos la sintaxis from <nombre_libreria> import <nombre_funcion>

from numpy.random import random

In [132]:
random(10)

array([ 0.10069931,  0.63590847,  0.71470881,  0.13174172,  0.99010419,
        0.44597673,  0.03638946,  0.09700602,  0.20483315,  0.09434063])

In [135]:
x=range(0,10, 0.5)
list(x)

TypeError: 'float' object cannot be interpreted as an integer

In [136]:
# Crear un arreglo de enteros que comience en 0 y termine en 10 (no incluído)

x=np.arange(0,10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [137]:
# Crear un arreglo de punto flotante que comience en 0 y termine en 10, con paso de 0.5

x=np.arange(0,10, 0.5, dtype=np.float64)
print(x)
print(x.dtype)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5]
float64


In [140]:
np.linspace(0,100, 6)

array([   0.,   20.,   40.,   60.,   80.,  100.])

In [141]:
x

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [142]:
# Usar funciones trigonométricas
# Numpy contiene una serie de constantes matemáticas. Usaremos Pi

y=np.sin(x*np.pi)
print(y)

[  0.00000000e+00   1.00000000e+00   1.22464680e-16  -1.00000000e+00
  -2.44929360e-16   1.00000000e+00   3.67394040e-16  -1.00000000e+00
  -4.89858720e-16   1.00000000e+00   6.12323400e-16  -1.00000000e+00
  -7.34788079e-16   1.00000000e+00   8.57252759e-16  -1.00000000e+00
  -9.79717439e-16   1.00000000e+00   1.10218212e-15  -1.00000000e+00]


In [143]:
# Usar funciones como potencia

y=np.power(x,2) # elevar cada elemento del arreglo x, a la segunda potencia
print(y)

[  0.     0.25   1.     2.25   4.     6.25   9.    12.25  16.    20.25  25.
  30.25  36.    42.25  49.    56.25  64.    72.25  81.    90.25]


In [145]:
x**2

array([  0.  ,   0.25,   1.  ,   2.25,   4.  ,   6.25,   9.  ,  12.25,
        16.  ,  20.25,  25.  ,  30.25,  36.  ,  42.25,  49.  ,  56.25,
        64.  ,  72.25,  81.  ,  90.25])

In [146]:
# Usar funciones como raíz cuadrada

y=np.sqrt(x) # raíz de a, del inglés "square root"
print(y)

[ 0.          0.70710678  1.          1.22474487  1.41421356  1.58113883
  1.73205081  1.87082869  2.          2.12132034  2.23606798  2.34520788
  2.44948974  2.54950976  2.64575131  2.73861279  2.82842712  2.91547595
  3.          3.082207  ]


In [147]:
x

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [148]:
x[10]=1000
x

array([  0.00000000e+00,   5.00000000e-01,   1.00000000e+00,
         1.50000000e+00,   2.00000000e+00,   2.50000000e+00,
         3.00000000e+00,   3.50000000e+00,   4.00000000e+00,
         4.50000000e+00,   1.00000000e+03,   5.50000000e+00,
         6.00000000e+00,   6.50000000e+00,   7.00000000e+00,
         7.50000000e+00,   8.00000000e+00,   8.50000000e+00,
         9.00000000e+00,   9.50000000e+00])

In [154]:
x=np.array([[1,2,3,4]])
print(x)
print(x.shape)

[[1 2 3 4]]
(1, 4)


In [155]:
y=np.array([x,x])
print(y)
print(y.shape)

[[[1 2 3 4]]

 [[1 2 3 4]]]
(2, 1, 4)


In [ ]:
from numpy import *

In [ ]:
sqrt(x)

Escribir *np.sqrt(x)* es mucho más breve que la alternativa de usar funciones nativas de Python: Calcular una a una las raíces cuadradas de cada elemento de *x*.

In [ ]:
result = []
for el in x:
    result.append(el**0.5)

print("\nUsando Python built-in: ", result)
print("\nUsando Numpy: ", y)

---

# Ejercicios

Realice los siguientes ejercicios. En caso de tener dudas, puede apoyarse con sus compañeros, preguntarle al profesor y hacer búsquedas en internet.

1. Cree una matriz de 7 columnas por 9 filas. Las primeras 3 columnas de la matriz tienen que tener el valor 0. La cuarta columna debe tener el valor 0.5, excepto por el último valor de esa columna, que tiene que ser 0.7. Las otras tres columnas deben tener el valor 1.

    Imprima la matriz y calcule las suma de los elementos de la última fila

2. La siguienteinstrucción crea una matriz aleatoria de 5 por 5 con valores entre 0 y 1
    `matriz_aleatoria=np.random.rand(5,5)` 

    Imprima las posiciones (Fila y columna) de los elementos de la matriz que son mayores que 0.5

In [ ]:
matriz_aleatoria=np.random.rand(5,5)
print(matriz_aleatoria)